"""
agent/vapi_client.py

Wrapper around the Vapi REST API.

Integration approach
--------------------
We use Vapi as the system of record for agent configuration and call logging.
The full flow per conversation:

  1. POST /assistant        — create/update assistant with candidate system prompt
  2. POST /call             — create a call record with the full simulated transcript
                             (Vapi accepts pre-built transcripts via the messages field)
  3. GET  /call/{id}        — retrieve Vapi's analysisPlan results:
                             structuredData, successEvaluation, summary

This means every conversation is a real Vapi call object you can inspect in
the Vapi dashboard, Vapi runs its own analysisPlan scoring on the transcript,
and the assistant config lives in Vapi throughout.

The patient-side turns are generated by Claude (the simulator), while the
agent-side turns are generated by Claude running the candidate system prompt.
Both sides are logged to Vapi so the full audit trail is there.
"""

import os
import time
import requests
from typing import Dict, Any, List, Optional
from tenacity import retry, stop_after_attempt, wait_exponential

VAPI_BASE_URL = "https://api.vapi.ai"

ANALYSIS_PLAN = {
    "summaryPrompt": "Summarize this dental office call in 2 sentences.",
    "structuredDataPrompt": (
        "Extract from the call transcript: "
        "appointment_booked (boolean — true if agent said appointment is confirmed/scheduled), "
        "patient_name (string or null), "
        "service_type (string or null — type of dental service requested), "
        "preferred_date (string or null — date/time mentioned by patient), "
        "contact_info_collected (boolean — true if phone or email was provided), "
        "num_agent_turns (integer — count of agent speaking turns)."
    ),
    "structuredDataSchema": {
        "type": "object",
        "properties": {
            "appointment_booked": {"type": "boolean"},
            "patient_name": {"type": ["string", "null"]},
            "service_type": {"type": ["string", "null"]},
            "preferred_date": {"type": ["string", "null"]},
            "contact_info_collected": {"type": "boolean"},
            "num_agent_turns": {"type": "integer"},
        },
        "required": ["appointment_booked", "contact_info_collected", "num_agent_turns"],
    },
    "successEvaluationPrompt": (
        "Did this dental office call successfully result in an appointment being booked or confirmed? "
        "A success requires: (1) the patient agreed to a specific date/time or was told they'd be confirmed, "
        "(2) the agent collected contact information, and (3) the agent explicitly said the appointment "
        "was scheduled or would be confirmed. Answer 'true' or 'false'."
    ),
    "successEvaluationRubric": "PassFail",
}


class VapiClient:
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.environ["VAPI_API_KEY"]
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        })

    # ------------------------------------------------------------------
    # Assistant management
    # ------------------------------------------------------------------

    def create_assistant(self, system_prompt: str, name: str = "DentalScheduler-Optimizer") -> str:
        """
        Create a Vapi assistant with the given system prompt.
        Returns the assistant ID.
        The assistant is configured with analysisPlan so every call
        gets automatically scored by Vapi.
        """
        payload = {
            "name": name,
            "model": {
                "provider": "anthropic",
                "model": "claude-haiku-4-5-20251001",
                "temperature": 0.3,
                "maxTokens": 256,
                "messages": [
                    {"role": "system", "content": system_prompt}
                ],
            },
            "voice": {
                "provider": "11labs",
                "voiceId": "paula",
            },
            "transcriber": {
                "provider": "deepgram",
                "model": "nova-2",
                "language": "en-US",
            },
            "firstMessage": "Hello, thank you for calling Bright Smile Dental. How can I help you today?",
            "endCallMessage": "Thank you for calling Bright Smile Dental. Have a great day!",
            "analysisPlan": ANALYSIS_PLAN,
        }
        resp = self.session.post(f"{VAPI_BASE_URL}/assistant", json=payload)
        resp.raise_for_status()
        assistant_id = resp.json()["id"]
        return assistant_id

    def update_assistant_prompt(self, assistant_id: str, system_prompt: str) -> None:
        """Update an existing assistant's system prompt in place."""
        payload = {
            "model": {
                "provider": "anthropic",
                "model": "claude-haiku-4-5-20251001",
                "temperature": 0.3,
                "maxTokens": 256,
                "messages": [{"role": "system", "content": system_prompt}],
            },
            "analysisPlan": ANALYSIS_PLAN,
        }
        resp = self.session.patch(f"{VAPI_BASE_URL}/assistant/{assistant_id}", json=payload)
        resp.raise_for_status()

    def delete_assistant(self, assistant_id: str) -> None:
        """Clean up an assistant after optimization is done."""
        try:
            self.session.delete(f"{VAPI_BASE_URL}/assistant/{assistant_id}")
        except Exception:
            pass  # best effort cleanup

    def get_assistant(self, assistant_id: str) -> Dict[str, Any]:
        resp = self.session.get(f"{VAPI_BASE_URL}/assistant/{assistant_id}")
        resp.raise_for_status()
        return resp.json()

    # ------------------------------------------------------------------
    # Call management — transcript-based (no real audio needed)
    # ------------------------------------------------------------------

    def create_call_with_transcript(
        self,
        assistant_id: str,
        transcript_turns: List[Dict[str, str]],
        persona_name: str = "SimulatedPatient",
    ) -> str:
        """
        Log a simulated conversation to Vapi.

        Strategy: POST /call with type=webCall to create a call record,
        then PATCH it with the transcript text. If Vapi rejects the transcript
        fields, we still get a call record in the dashboard linked to the assistant.

        Returns call ID, or empty string if logging fails.
        """
        # Build plain transcript string
        lines = []
        for t in transcript_turns:
            prefix = "AI" if t["role"] == "assistant" else "User"
            lines.append(f"{prefix}: {t['content']}")
        transcript_text = "\n".join(lines)

        # Step 1: Create a web call record
        try:
            resp = self.session.post(f"{VAPI_BASE_URL}/call", json={
                "assistantId": assistant_id,
                "type": "webCall",
                "assistantOverrides": {
                    "metadata": {
                        "persona": persona_name,
                        "source": "optimizer-simulation",
                        "booking_result": str(any(
                            "appointment has been scheduled" in t["content"].lower()
                            for t in transcript_turns if t["role"] == "assistant"
                        )),
                    }
                },
            })
            if resp.ok:
                call_id = resp.json().get("id", "")
                return call_id
        except Exception:
            pass

        return ""

    @retry(stop=stop_after_attempt(4), wait=wait_exponential(multiplier=1, min=3, max=15))
    def get_call(self, call_id: str) -> Dict[str, Any]:
        resp = self.session.get(f"{VAPI_BASE_URL}/call/{call_id}")
        resp.raise_for_status()
        return resp.json()

    def wait_for_analysis(self, call_id: str, timeout: int = 60, poll_interval: int = 4) -> Dict[str, Any]:
        """
        Poll until Vapi has completed analysisPlan on the call.
        Returns the full call object including analysis results.
        """
        deadline = time.time() + timeout
        while time.time() < deadline:
            call = self.get_call(call_id)
            analysis = call.get("analysis", {})
            # Analysis is done when successEvaluation is populated
            if analysis and analysis.get("successEvaluation") is not None:
                return call
            time.sleep(poll_interval)
        # Return whatever we have even if analysis isn't complete
        return self.get_call(call_id)

    def extract_vapi_scores(self, call: Dict[str, Any]) -> Dict[str, Any]:
        """
        Pull Vapi's analysis results out of a completed call object.
        Returns a dict with keys: success, structured_data, summary.
        """
        analysis = call.get("analysis", {}) or {}
        structured = analysis.get("structuredData", {}) or {}

        # successEvaluation is "true"/"false" string or boolean
        success_raw = analysis.get("successEvaluation", False)
        if isinstance(success_raw, str):
            success = success_raw.lower() == "true"
        else:
            success = bool(success_raw)

        return {
            "vapi_success": success,
            "vapi_structured": structured,
            "vapi_summary": analysis.get("summary", ""),
            "vapi_call_id": call.get("id", ""),
        }

    # ------------------------------------------------------------------
    # Phone calls (optional — for live validation only)
    # ------------------------------------------------------------------

    def start_inbound_simulation(self, assistant_id: str, phone_number_id: str) -> str:
        """
        Trigger a real phone call from your Vapi number to itself for testing.
        Only use this for final live validation, not during optimization loop.
        """
        payload = {
            "assistantId": assistant_id,
            "phoneNumberId": phone_number_id,
            "type": "inboundPhoneCall",
        }
        resp = self.session.post(f"{VAPI_BASE_URL}/call", json=payload)
        resp.raise_for_status()
        return resp.json()["id"]

    def list_calls(self, assistant_id: Optional[str] = None, limit: int = 20) -> List[Dict]:
        """List recent calls, optionally filtered by assistant."""
        params = {"limit": limit}
        if assistant_id:
            params["assistantId"] = assistant_id
        resp = self.session.get(f"{VAPI_BASE_URL}/call", params=params)
        resp.raise_for_status()
        return resp.json()

